#!/bin/bash

# assign variables
ACTION=${1}
version=1.0.1

function delete_file() {

rm "${1}-54321"
}

function create_file() {

touch "${1}-54321"
}

function show_version() {

echo $version
}

function display_help() {

cat << EOF
Usage: ${0} {-d|--delete|-c|--create|-h|--help|-v|--version} <filename>

OPTIONS:
	-d | --delete	Remove a file
	-c | --create	Create a new file
	-h | --help	Display the command help
	-v | --version	Show script version

Examples:
	Remove a file:
		$ ${0} -d foo
	Create a new file:
		$ ${0} -c foo.txt
	Display help:
		$ ${0} -h
	Show version:
		$ ${0} -v

EOF
}

case "$ACTION" in
	-d|--delete)
		delete_file "${2:-server}"
		;;
	-h|--help)
		display_help
		;;
	-c|--create)
		create_file "${2:-server}"
		;;
	-v|--version)
		show_version
		;;
	*)
	echo "Usage ${0} {-c|-h}"
	exit 1
esac
